### PR TITLE
Fix warnings and update ios 7

### PR DESCRIPTION
**Pull request by ezefranca**

### CODE REVIEW

**Comment by alvaromb** [comment]
Hello @ezefranca! this PR looks good to me, have you tested if the Example works also?

**Comment by ezefranca** [comment]
Hi @alvaromb . Yes I tested, I did the PR this because I'm using this pod and the warnings are appearing in my project 😂.
Thanks.

**Comment by alvaromb** [comment]
Cool! I don't have a lot of time to test this project nowadays so I'll trust your skills and merge the PR :shipit: 

Let me know if you have a cool idea or something, I'll be more than happy to update or improve what this tiny button thing does :)

**Comment by ezefranca** [comment]
#hacktoberfest :+1:

**Pull request merged**
